version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "test"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Africa/Lagos"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - "dependencies"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "patch"
          - "minor"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "patch"
          - "minor"
    ignore:
      - dependency-name: "react-router"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@tanstack/react-table"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "test"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Africa/Lagos"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ci"