import { spawn } from "node:child_process";
import { rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { MongoMemoryServer } from "mongodb-memory-server";

/**
 * End-to-end dev server launcher.
 *
 * Boots an in-memory MongoDB, writes a temporary `.env.e2e` overriding the
 * DB/URLs, then spawns `react-router dev --mode e2e`. The env file must exist
 * BEFORE the dev server boots (Vite loads `.env.e2e` via `--mode e2e`), which
 * is why this lives in the webServer command rather than Playwright's
 * globalSetup (Playwright starts the webServer before globalSetup runs).
 *
 * Deletes `.env.e2e` and stops MongoDB on exit.
 */
const ENV_FILE = join(process.cwd(), ".env.e2e");

const override = [
  `# Generated by scripts/dev-e2e.ts — deleted on exit`,
  `DATABASE_URL=__DB_URI__`,
  `DATABASE_NAME=bc007_e2e`,
  `CLIENT_URL=http://localhost:5701`,
  `BETTER_AUTH_URL=http://localhost:5701`,
  `BETTER_AUTH_SECRET=e2e-better-auth-secret`,
  `EMAIL_HOST=smtp.test`,
  `EMAIL_PORT=587`,
  `EMAIL_USER=e2e@test`,
  `EMAIL_PASSWORD=e2e-password`,
  `QSTASH_TOKEN=e2e-qstash-token`,
  `QSTASH_URL=https://qstash.test`,
  `UPSTASH_REDIS_REST_URL=https://test.upstash.io`,
  `UPSTASH_REDIS_REST_TOKEN=e2e-token`,
  `CLOUDINARY_CLOUD_NAME=test`,
  `CLOUDINARY_API_KEY=test`,
  `CLOUDINARY_SECRET_KEY=test`,
  `CLOUDINARY_UPLOAD_PRESET=test`,
  `OPENCODE_ZEN_API_KEY=e2e`,
  `PAYSTACK_SECRET_KEY=test`,
  ``,
].join("\n");

let mongod: MongoMemoryServer | undefined;

const cleanup = async () => {
  await rm(ENV_FILE, { force: true }).catch(() => undefined);
  await mongod?.stop().catch(() => undefined);
};

async function main() {
  mongod = await MongoMemoryServer.create({
    instance: { storageEngine: "wiredTiger" },
  });
  await writeFile(ENV_FILE, override.replace("__DB_URI__", mongod.getUri()));

  const child = spawn(
    "node_modules/.bin/react-router",
    ["dev", "--mode", "e2e", "--port", "5701", "--strictPort"],
    { stdio: "inherit" },
  );

  const forward = (signal: NodeJS.Signals) => () => child.kill(signal);
  process.on("SIGINT", forward("SIGINT"));
  process.on("SIGTERM", forward("SIGTERM"));

  child.on("exit", async (code) => {
    await cleanup();
    process.exit(code ?? 0);
  });
}

main().catch(async (err) => {
  console.error(err);
  await cleanup();
  process.exit(1);
});
